;------------------------------------------------------------------------
;  conio.inc
;  Copyright (c)2021 Kevin Boone, GPL v3.0
;------------------------------------------------------------------------

	.Z80

	external exit 
	external newline
	; external puth8
	; external puth16
	external putch
	; external putdigit 
	external puts 
	external puts7bit
	external space 
	; external puth8

